### ISSUE TITLE
burp版本要求太高了，16g电脑带不动,新版burp用起来太卡

### ISSUE THREAD

**Issue by panzhen1992** [outlaws-bai/Galaxy#11]
burp版本要求太高了，16g电脑带不动,新版burp用起来太卡

**Comment by outlaws-bai** [comment]
啊？我16G笔记本都可以的

**Comment by codeyso** [comment]
同需求^.^，低版本能用嘛

**Comment by panzhen1992** [comment]
2023年版本的burp用起来太卡，[Galaxy](https://github.com/outlaws-bai/Galaxy)这个22年 版本的burp不支持，电脑跑不动呀，同事他们也都是用2021或者22版本的burp

**Comment by outlaws-bai** [comment]
项目是基于 Burp的Montoya API 开发的，这个对 Burp 版本有强制要求

**Comment by WarmStyle** [comment]
22版本的burp加载报错怎么解决呀
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at burp.cs1.a(Unknown Source)
	at burp.cs1.<init>(Unknown Source)
	at burp.a6l.a(Unknown Source)
	at burp.c7v.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by outlaws-bai** [comment]
> 22版本的burp加载报错怎么解决呀
> java.lang.ClassNotFoundException: burp.BurpExtender
> 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
> 	at java.base/java.lang.Class.forName0(Native Method)
> 	at java.base/java.lang.Class.forName(Class.java:466)
> 	at burp.cs1.a(Unknown Source)
> 	at burp.cs1.<init>(Unknown Source)
> 	at burp.a6l.a(Unknown Source)
> 	at burp.c7v.lambda$panelLoaded$0(Unknown Source)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> 	at java.base/java.lang.Thread.run(Thread.java:831)
> 
> 

版本过低
