### ISSUE TITLE
安装Galaxy-3.2.0-grpc.jar报错（ClassNotFoundException: org.graalvm.polyglot.Engine），注释乱码

### ISSUE THREAD

**Issue by miaoxu1com** [outlaws-bai/Galaxy#17]
系统信息：
OS 名称:          Microsoft Windows 10 专业版

BurpSuite版本：
V2024.8.1

BurpSuite配置
Java environment配置目录下存在文件：
jython-standalone-2.7.4.jar

问题1.
py脚本注释乱码截图
![image](https://github.com/user-attachments/assets/204a76fc-c0e3-4fa2-8d88-7ba9b60375e5)

问题2
OutPut输出：
Welcome to Galaxy
Author -> outlaws-bai && tdyj && lwhispers
Github -> https://github.com/outlaws-bai/Galaxy
Version -> 3.2.0
ERROR输出报错信息：
java.lang.ClassNotFoundException: org.graalvm.polyglot.Engine
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.m2sec.core.common.Helper.checkDep(Helper.java:75)
	at org.m2sec.core.common.Helper.init(Helper.java:38)
	at org.m2sec.Galaxy.initialize(Galaxy.java:31)
	at burp.Zzbb.Zs(Unknown Source)
	at burp.Zf5g.Zt(Unknown Source)
	at burp.Zf5e.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
@outlaws-bai
 #16

**Comment by miaoxu1com** [comment]
@outlaws-bai 感觉是一个Bug可以设置一个Bug标签方便其他人注意到

**Comment by outlaws-bai** [comment]
问题 1：请尝试修改 burp 的编码为 utf-8
问题 2：下个小版本修复

**Comment by outlaws-bai** [comment]
https://github.com/outlaws-bai/Galaxy/commit/e66c2460ac02db288cfc9a01a4c54d3daa0ec80c

**Comment by miaoxu1com** [comment]
@outlaws-bai 
这个我自己摸索着，编译了一版，问题2已解决
#16 按照，问题1也已经解决
有一个新的问题这里是每个jar都会有一个tab吗，是否可以优化成放在一个tab中
![image](https://github.com/user-attachments/assets/cdf32181-7f6d-4f93-8fcf-270d1e64dd0d)

**Comment by miaoxu1com** [comment]
如果要是 搞不了 我就把这个问题关闭了

**Comment by outlaws-bai** [comment]
这个优化不了，burp 自动的，每个插件的 tab 是隔离的，我的想法是每个人一般只需要一种 jar 包吧，是出于什么需求下了三个呢 -。-
问题可以先不关，让其他人知道3.2.0-grpc 的jar 包有问题吧

**Comment by miaoxu1com** [comment]
@outlaws-bai 好的  主要是我看 每个tab中都有另外两个中没有的 hook方式 所以  问一下

**Comment by miaoxu1com** [comment]
@outlaws-bai 另外 我补充一点 就是 git 上的代码少了 一个 gradle-wrapper.jar文件导致，生成时需要自己重新生成，否则会报错，可能是git上传时，jar文件被忽略了，我猜测的，可以加上方便其他人构建时不用重新生成了

**Comment by outlaws-bai** [comment]
@miaoxu1com 好勒，没问题，感谢建议

**Comment by outlaws-bai** [comment]
3.2.1已修复
